### ISSUE TITLE
problem to run Training (make train ....)

### ISSUE THREAD

**Issue by AmineManso** [gnocchiflette/NTU-RGB-D#37]
Hi !

First I run the data preprocessing section and it worked.
Then when I tried to run the Training section ( make train --[args] ...) it shows this error:
`
========== SUMMARY ==========
-> h5 dataset folder path : /path/FUSION-human-action-recognition/data/processed/old_h5_folder_2/
-> output_folder : /path/FUSION-human-action-recognition/models/
-> evaluation_type : cross_subject
-> model_type : FUSION
-> use pose : True
-> use ir : True
-> pretrained : True
-> use cropped ir : True
-> fusion scheme : CONCAT
-> optimizer : ADAM
-> learning rate : 0.0001
-> weight decay : 0.0
-> gradient threshold : 10.0
-> max epochs : 15
-> batch size : 16
-> accumulation steps : 1
-> sub_sequence_length : 20
-> augment_data : True
-> mirror skeleton : False
-> evaluate_test : True
-> seed : 0

Computing c_min and c_max. This takes a while ...
Done !
0 - 0.0/107
Traceback (most recent call last):
  File "src/models/train_model.py", line 254, in <module>
    validation_generator)
  File "/path/FUSION-human-action-recognition/src/models/train_utils.py", line 261, in train_model
    out = model(X)
  File "/user1/path/.conda/envs/fusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/path/FUSION-human-action-recognition/src/models/pose_ir_fusion.py", line 106, in forward
    out_pose = self.pose_net(X_skeleton)[:, :, 0, 0]  # shape (batch_size, 512)
  File "/user1/path/.conda/envs/fusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/user1/path/.conda/envs/fusion/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/user1/path/.conda/envs/fusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/user1/path/.conda/envs/fusion/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/user1/path/.conda/envs/fusion/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
make: *** [train] Erreur 1
`

Could you help detect and solve the problem

Thanks in advance for helping !!!!

**Comment by 339238** [comment]
Hi！
May I ask if you have solved this problem？
