### ISSUE TITLE
Error in making dataset (IR_Cropped)

### ISSUE THREAD

**Issue by Mansoor35** [gnocchiflette/NTU-RGB-D#7]
Hi 

I am making dataset files by running the file "make dataset". I have made IR, SKELETON and IR_SKELETON datasets but when I run the code for IR_CROPPED, I get following error. 

Traceback (most recent call last):
  File "C:/Users/mteevno2/OneDrive - City University of Hong Kong/coding/FUSION-human-action-recognition-master/FUSION-human-action-recognition-master/src/data/make_dataset.py", line 74, in <module>
    create_h5_ir_cropped_dataset_from_h5(arg.data_path,
  File "C:\Users\mteevno2\OneDrive - City University of Hong Kong\coding\FUSION-human-action-recognition-master\FUSION-human-action-recognition-master\src\data\make_dataset_utils.py", line 209, in create_h5_ir_cropped_dataset_from_h5
    video_data = ir_dataset[sequence_name]["ir"][:]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\mteevno2\anaconda3\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'S001C001P001R001A015' doesn't exist)"

Note: I have not downloaded all the NTU dataset, rather I have only worked on One folder of IR, one file of Skeleton. 

Thank you.

**Comment by adeboissiere** [comment]
Hi,

Sorry for the delay. You need to have ir.h5 created before creating ir_cropped.h5. Let me know if that works.
